_BASE: ../OTAM_base.yaml
TASK_TYPE: few_shot_action
RANDOM_SEED: 8
TRAIN:
  ENABLE: true
  USE_CLASSIFICATION: true
  USE_LOCAL: false
  USE_CLASSIFICATION_VALUE: 0.8
  NUM_CLASS: 64
  DATASET: Ssv2_few_shot
  META_BATCH: true  # meta or not
  NUM_SAMPLES: 1000000
  USE_RECONS: true 
  RECONS_COFF: 0.1
  USE_MOTION: true
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 6 
  QUERY_PER_CLASS_TEST: 1
  USE_CONTRASTIVE: true
  USE_CONTRASTIVE_COFF: 0.05
  NUM_TRAIN_TASKS: 50000
  NUM_TEST_TASKS: 10000
  VAL_FRE_ITER: 1000
  BATCH_SIZE: 4  # Same with NUM_GPUS
  BATCH_SIZE_PER_TASK: 4
  CHECKPOINT_FILE_PATH: ""
  EVAL_PERIOD: 2
  NUM_FOLDS: 1

AUGMENTATION:
  COLOR_AUG: false
  NO_RANDOM_ERASE: true
  SUPPORT_QUERY_DIFF: true

TEST:
  ENABLE: false
  DATASET: Ssv2_few_shot
  BATCH_SIZE: 4  # Same with NUM_GPUS
  TEST_SET: val
  NUM_ENSEMBLE_VIEWS: 1
  SPATIAL_CROPS: cctltr
  AUTOMATIC_MULTI_SCALE_TEST: false
  UPLOAD_CLASSIFIER_RESULTS: true

DATA:
  DATA_ROOT_DIR: /fs/vulcan-projects/VidGram/ssv2_mp4
  ANNO_DIR: ./configs/projects/MoLo/ssv2_full/
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 50
  SAMPLING_UNIFORM: false
  TRAIN_JITTER_SCALES: [256, 256]
  TRAIN_CROP_SIZE: 224 # 84  # 224
  TEST_CROP_SIZE: 224
  TEST_SCALE: 256
  TEST_CENTER_CROP: true
  CLIP_INTERVAL: 8
  FPS: 12
  TARGET_FPS: 12

LOG_PERIOD: 50
SOLVER:
  BASE_LR: 0.0001  # 0.0001 # 0.0005
  LR_POLICY: steps_with_relative_lrs
  STEPS_ITER: 6000
  STEPS: [0, 6, 9]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 1
  WARMUP_START_LR: 0.00002
  OPTIM_METHOD: adam
  DAMPENING: 0.0
  NESTEROV: true
# add bn, use same lr settings as server

VIDEO:
  HEAD:
    NAME: CNN_BiMHM_MoLo  
    BACKBONE_NAME: "resnet50"

  BACKBONE:
    META_ARCH: Identity

NUM_GPUS: 4
OUTPUT_DIR: output/MoLo_SSv2_Full_1shot


